# Generated by Django 5.1.1 on 2024-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_goal_points_category_goal_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="recurrent_until",
            field=models.CharField(
                blank=True,
                choices=[("forever", "Forever"), ("date", "Until Date")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="until_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
